FROM golang:1.20 as go-build
WORKDIR /gotty
COPY . /gotty
RUN CGO_ENABLED=0 make gotty-no-frontend

FROM python:3.11-alpine
RUN apk update && \
    apk upgrade && \
    apk --no-cache add ca-certificates bash
WORKDIR /root
COPY --from=go-build /gotty/gotty /usr/bin/
CMD ["gotty",  "-w", "bash"]
